import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillInstagram, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import deved from "../public/myavatar.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";


export default function Home() {
  const [darMode, setdarkMode] = useState(false);
  return (
    <div className={darMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white text-black px-10 pb-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl dark:text-gray-200">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => {
                    setdarkMode(!darMode);
                  }}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1K4CT2FbpHH-kra68Gb6HQZSSQqW7LOvi/view?usp=share_link"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center sm:p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl text-[30px]">
              Shan Khan
            </h2>
            <h3 className="text-xl py-2 md:text-3xl dark:text-gray-400">
              Software Developer
            </h3>
            <p className=" text-md sm:py-5 leading-8 text-gray-800 md:text-xl max-w-2xl sm:mx-auto text-justify dark:text-white">
              Shan Khan is a skilled software developer with expertise in a
              variety of technologies including Core Java, Spring Boot, React
              JS, JavaScript, Git, GitHub, Firebase, HTML, CSS, and Bootstrap.
              With a strong understanding of these technologies, Shan is capable
              of developing robust and scalable applications. Additionally, Shan
              is well-versed in using Git and GitHub for version control, and
              Firebase for cloud services. With an eye for design, Shan is
              proficient in HTML, CSS, and Bootstrap, enabling them to create
              visually appealing and responsive applications. With their
              comprehensive knowledge of these technologies, Shan is an asset to
              any team looking to build high-quality software.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-50">
            <AiFillGithub className="hover:text-gray-800 cursor-pointer" />
            <AiFillLinkedin className="hover:text-gray-800 cursor-pointer" />
            <AiFillInstagram className="hover:text-gray-800 cursor-pointer" />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className=" text-3xl py-1 dark:text-gray-400">
              Services I offer
            </h3>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-white text-justify">
              As a developer with expertise in Java Spring Boot, ReactJS,
              Firebase, C, C++, and JavaScript, I offer a range of services that
              can help businesses achieve their goals.
            </p>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-white text-justify">
              My experience includes developing full-stack web applications
              using Java Spring Boot and ReactJS, building mobile applications
              for iOS and Android platforms using Firebase, developing backend
              services using Java Spring Boot, and creating user interfaces with
              ReactJS.
            </p>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-white text-justify">
              In addition, I have experience developing desktop applications for
              Windows, Linux, and macOS using C and C++, as well as developing
              games for various platforms using these languages.
            </p>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-white text-justify">
              I am also available for custom software development services,
              where I can work with businesses to build custom software
              solutions that meet their specific requirements.
            </p>
            <p className=" text-md py-2 leading-8 text-gray-800 dark:text-white text-justify">
              If you are looking for a skilled developer with a proven track
              record of delivering high-quality solutions, I would be happy to
              discuss how I can help you achieve your goals. Contact me today to
              learn more about my services and how I can help your business
              succeed.
            </p>
          </div>
          <div className=" lg:flex gap-10">
            <div className="text-center flex flex-col items-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={design} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facere
                porro quisquam tempore doloremque sit veniam earum corporis esse
                numquam! Ipsam quisquam voluptate deserunt quia id eum, illum
                consequatur beatae molestias.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I used</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center flex flex-col items-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={code} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facere
                porro quisquam tempore doloremque sit veniam earum corporis esse
                numquam! Ipsam quisquam voluptate deserunt quia id eum, illum
                consequatur beatae molestias.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I used</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center flex flex-col items-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image src={consulting} width={100} height={100} />
              <h3 className=" text-lg font-medium pt-8 pb-2">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Facere
                porro quisquam tempore doloremque sit veniam earum corporis esse
                numquam! Ipsam quisquam voluptate deserunt quia id eum, illum
                consequatur beatae molestias.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I used</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div className="">
            <h3 className="text-3xl py-1 dark:text-gray-400">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sapiente
              obcaecati laudantium aut numquam maiores mollitia sed facere sint
              atque similique illo corrupti autem porro doloribus odio a,
              temporibus neque quasi!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"responsive"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"responsive"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"responsive"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"responsive"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"responsive"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout={"responsive"}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
